export default {
  WAIT_FOR_RESPONSE: 'WAIT_FOR_RESPONSE',
  AUTH_SUCCESS_AND_SAVE_TOKEN: 'AUTH_SUCCESS_AND_SAVE_TOKEN',
  AUTH_FAILED: 'AUTH_FAILED',
  AFTER_RESPONSE: 'AFTER_RESPONSE',
  CLEAR_TOKEN_AND_LOGOUT: 'CLEAR_TOKEN_AND_LOGOUT',
  SHOW_LOGIN_FORM: 'SHOW_LOGIN_FORM',
  // 定义任务相关的mutation type
  UPDATEING_TASK: 'UPDATEING_TASK',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  ADD_TASK_ERROR: 'ADD_TASK_ERROR',
  LOADING_TASKS: 'LOADING_TASKS',
  LOAD_TASK_SUCCESS: 'LOAD_TASK_SUCCESS',
  LOAD_TASK_FAILED: 'LOAD_TASK_FAILED',
  // 定义回答相关的mutation type
  LOADING_ANSWERS: 'LOADING_ANSWERS',
  LOAD_ANSWERS_SUCCESS: 'LOAD_ANSWERS_SUCCESS',
  LOAD_ANSWERS_FAILED: 'LOAD_ANSWERS_FAILED',
    // 定义问卷相关的mutation type
  UPDATEING_QUESTIONNAIRE: 'UPDATEING_QUESTIONNAIRE',
  ADD_QUESTIONNAIRE_SUCCESS: 'ADD_QUESTIONNAIRE_SUCCESS',
  ADD_QUESTIONNAIRE_ERROR: 'ADD_QUESTIONNAIRE_ERROR',
  LOADING_QUESTIONNAIRES: 'LOADING_QUESTIONNAIRES',
  LOAD_QUESTIONNAIRE_SUCCESS: 'LOAD_QUESTIONNAIRE_SUCCESS',
  LOAD_QUESTIONNAIRE_FAILED: 'LOAD_QUESTIONNAIRE_FAILED',
  // 定义用户相关的mutation type
  LOADING_USER_DATA: 'LOADING_USER_DATA',
  LOAD_USER_DATA_SUCCESS: 'LOAD_USER_DATA_SUCCESS',
  LOAD_USER_DATA_FAILED: 'LOAD_USER_DATA_FAILED'
}




